spring:
  application:
    name: system-gym
  datasource:
    url: jdbc:postgresql://system-gym:5432/gym
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
